#!/usr/bin/env python
"""Render docs/rules/DJS.md from the rule registry.

Rule documentation written by hand goes stale, and stale security
documentation is worse than none: it describes a rule that no longer behaves
that way, and the reader has no way to tell. Every field in the page already
exists on the rule -- title, grade, rationale, remediation, references and
limitations -- so the page is generated and CI fails if the committed copy is
not what the code currently says.

``--check`` verifies without writing, which is what CI runs.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from djaudit import registry
from djaudit.models import Family

OUT = Path(__file__).resolve().parent.parent / "docs" / "rules" / "DJS.md"

HEADER = """<!--
Generated by scripts/gen_rule_docs.py. Do not edit by hand.

Every field below lives on the rule itself, so the way to change this page is
to change the rule and run the script. CI checks the two agree.
-->

# `DJS` — settings and deployment hardening

{count} rules covering the settings that decide whether a Django deployment is
safe to expose: what it admits about itself, what it puts on the wire, what it
keeps out of the repository, and what it leaves switched on that should not be.

Every rule here is **static**. Nothing is imported and nothing is executed, so
the analysis works on a checkout with none of the target's dependencies
installed — and it never sees the deployment. That boundary is why each rule
carries a *limitations* section, and why confidence is a first-class field
rather than a footnote.

## How to read a grade

**Severity** is what happens if the finding is real. **Confidence** is how sure
we are that it is. They move independently: an unencrypted database session is
serious whether or not we can prove it happens, and a setting we read exactly
may still be overridden by an environment we cannot see.

| Confidence | Meaning |
|---|---|
| `certain` | Read directly, and nothing outside the repo changes what it means. |
| `firm` | Read directly, on one ordinary assumption — usually that this module ships. |
| `tentative` | The value, or its consequence, depends on something the source lacks. |

The CLI shows `low` severity and `firm` confidence and above by default, so a
`tentative` finding is deliberately invisible until asked for:

```console
$ djaudit run . --min-severity info --min-confidence tentative
```

## Rules

| Rule | Title | Severity | Confidence |
|---|---|---|---|
{index}
"""

SECTION = """
---

### {id} — {title}

**Severity** {severity} · **Confidence** {confidence} · **Tier** {tier}

**What it means.** {rationale}

**How to fix it.** {remediation}

**What this rule cannot see.**

{limitations}

**References**

{references}
"""


def slug(rule_id: str, title: str) -> str:
    """Reproduce GitHub's heading anchor for ``### {id} — {title}``.

    GitHub lowercases, drops punctuation other than hyphen and underscore, and
    turns each remaining space into a hyphen. The em dash disappears and the
    spaces on either side of it survive, which is why every anchor here has a
    double hyphen after the rule id.
    """
    text = f"{rule_id} — {title}".lower()
    kept = "".join(c if (c.isalnum() or c in "-_ ") else "" for c in text)
    return kept.replace(" ", "-")


def render() -> str:
    registry._load_builtin_rules()
    rules = sorted(
        (r for r in registry.all_rules() if r.meta.family is Family.DJS),
        key=lambda r: r.meta.id,
    )

    index = "\n".join(
        f"| [`{r.meta.id}`](#{slug(r.meta.id, r.meta.title)}) "
        f"| {r.meta.title} | {r.meta.severity.value} | {r.meta.confidence.value} |"
        for r in rules
    )

    body = "".join(
        SECTION.format(
            id=r.meta.id,
            title=r.meta.title,
            severity=r.meta.severity.value,
            confidence=r.meta.confidence.value,
            tier=r.meta.tier.value,
            rationale=r.meta.rationale,
            remediation=r.meta.remediation,
            limitations="\n".join(f"- {item}" for item in r.meta.limitations),
            references="\n".join(f"- <{url}>" for url in r.meta.references),
        )
        for r in rules
    )

    return HEADER.format(count=len(rules), index=index) + body


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    rendered = render()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""

    if args.check:
        if current != rendered:
            print(
                f"RULE DOCS STALE: {OUT.relative_to(OUT.parent.parent.parent)} does not "
                "match the registry; run scripts/gen_rule_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"rule docs current: {current.count('### DJS-')} rules documented")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
