#!/usr/bin/env python
"""Render one page per rule family under docs/rules/ from the registry.

Rule documentation written by hand goes stale, and stale security
documentation is worse than none: it describes a rule that no longer behaves
that way, and the reader has no way to tell. Every field in the page already
exists on the rule -- title, grade, rationale, remediation, references and
limitations -- so the page is generated and CI fails if the committed copy is
not what the code currently says.

Only the family blurb is written by a human, because it is the one thing no
rule knows: what the family is *for*. Everything else is transcribed. A family
with rules and no blurb is an error rather than a page with a gap, so adding a
family cannot quietly ship an unexplained page.

``--check`` verifies without writing, which is what CI runs.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from djaudit import registry
from djaudit.models import Family
from djaudit.registry import Rule

DOCS = Path(__file__).resolve().parent.parent / "docs" / "rules"


@dataclass(frozen=True)
class Blurb:
    """The part of a family page that the rules cannot supply."""

    heading: str
    """What follows the family id in the page title."""

    summary: str
    """One paragraph on what the family covers. ``{count}`` is substituted."""

    scope: str
    """What the family reads, and what it therefore cannot see."""


BLURBS: dict[Family, Blurb] = {
    Family.DJS: Blurb(
        heading="settings and deployment hardening",
        summary=(
            "{count} rules covering the settings that decide whether a Django deployment is\n"
            "safe to expose: what it admits about itself, what it puts on the wire, what it\n"
            "keeps out of the repository, and what it leaves switched on that should not be."
        ),
        scope=(
            "Every rule here is **static**. Nothing is imported and nothing is executed, so\n"
            "the analysis works on a checkout with none of the target's dependencies\n"
            "installed — and it never sees the deployment. That boundary is why each rule\n"
            "carries a *limitations* section, and why confidence is a first-class field\n"
            "rather than a footnote."
        ),
    ),
    Family.DJA: Blurb(
        heading="API authorization and data exposure",
        summary=(
            "{count} rules on the two questions a REST API answers on every request: who is\n"
            "allowed to ask, and what comes back. They read Django REST Framework's own\n"
            "vocabulary — routers, viewsets, `permission_classes`, `get_queryset`,\n"
            "serializer `Meta`, filter backends, throttles — and follow it from the URL\n"
            "that reaches a view through to the model field that leaves in the response."
        ),
        scope=(
            "Every rule here is **static**, and that boundary bites harder than it does for\n"
            "`DJS`, because authorization is the part of a codebase most often decided at\n"
            "runtime. A permission named in settings may be replaced per view; a queryset\n"
            "may be narrowed by a mixin three classes up; `validate()` may reject exactly\n"
            "the request the serializer appears to accept. Where the answer lives somewhere\n"
            "the source does not say, these rules lower confidence rather than guess —\n"
            "several ship `tentative` by design and stay invisible at the default threshold\n"
            "until asked for."
        ),
    ),
    Family.DJD: Blurb(
        heading="data model and schema design",
        summary=(
            "{count} rules on the model layer itself — what a column is allowed to hold, what\n"
            "happens to a row when the row it points at is deleted, and what order a query\n"
            "returns when nobody asked for one. These are not vulnerabilities. They are the\n"
            "decisions that are cheap to change while the table is empty and expensive\n"
            "afterwards."
        ),
        scope=(
            "Every rule here is **static** and reads the model graph: field declarations and\n"
            "their arguments, `Meta`, and inheritance within the project. It does not read\n"
            "migrations, so it cannot tell a column that has always been nullable from one\n"
            "made nullable last week, and it does not read the database, so it cannot say\n"
            "how many rows actually hold the value it is describing."
        ),
    ),
}

HEADER = """<!--
Generated by scripts/gen_rule_docs.py. Do not edit by hand.

Every field below lives on the rule itself, so the way to change this page is
to change the rule and run the script. CI checks the two agree.
-->

# `{family}` — {heading}

{summary}

{scope}

## How to read a grade

**Severity** is what happens if the finding is real. **Confidence** is how sure
we are that it is. They move independently: an unencrypted database session is
serious whether or not we can prove it happens, and a setting we read exactly
may still be overridden by an environment we cannot see.

| Confidence | Meaning |
|---|---|
| `certain` | Read directly, and nothing outside the repo changes what it means. |
| `firm` | Read directly, on one ordinary assumption — usually that this module ships. |
| `tentative` | The value, or its consequence, depends on something the source lacks. |

The CLI shows `low` severity and `firm` confidence and above by default, so a
`tentative` finding is deliberately invisible until asked for:

```console
$ djaudit run . --min-severity info --min-confidence tentative
```

## Rules

| Rule | Title | Severity | Confidence |
|---|---|---|---|
{index}
"""

SECTION = """
---

### {id} — {title}

**Severity** {severity} · **Confidence** {confidence} · **Tier** {tier}

**What it means.** {rationale}

**How to fix it.** {remediation}

**What this rule cannot see.**

{limitations}

**References**

{references}
"""


def slug(rule_id: str, title: str) -> str:
    """Reproduce GitHub's heading anchor for ``### {id} — {title}``.

    GitHub lowercases, drops punctuation other than hyphen and underscore, and
    turns each remaining space into a hyphen. The em dash disappears and the
    spaces on either side of it survive, which is why every anchor here has a
    double hyphen after the rule id.
    """
    text = f"{rule_id} — {title}".lower()
    kept = "".join(c if (c.isalnum() or c in "-_ ") else "" for c in text)
    return kept.replace(" ", "-")


def documented_families() -> dict[Family, list[type[Rule]]]:
    """Families that have rules, keyed in the taxonomy's own order."""
    registry._load_builtin_rules()
    found: dict[Family, list[type[Rule]]] = {}
    for rule in sorted(registry.all_rules(), key=lambda r: r.meta.id):
        found.setdefault(rule.meta.family, []).append(rule)
    return {family: found[family] for family in Family if family in found}


def render(family: Family, rules: list[type[Rule]]) -> str:
    blurb = BLURBS.get(family)
    if blurb is None:
        raise SystemExit(
            f"RULE DOCS: {family.value} has {len(rules)} rules and no blurb in "
            "scripts/gen_rule_docs.py. A page cannot say what a family is for "
            "unless somebody writes it."
        )

    index = "\n".join(
        f"| [`{r.meta.id}`](#{slug(r.meta.id, r.meta.title)}) "
        f"| {r.meta.title} | {r.meta.severity.value} | {r.meta.confidence.value} |"
        for r in rules
    )

    body = "".join(
        SECTION.format(
            id=r.meta.id,
            title=r.meta.title,
            severity=r.meta.severity.value,
            confidence=r.meta.confidence.value,
            tier=r.meta.tier.value,
            rationale=r.meta.rationale,
            remediation=r.meta.remediation,
            limitations="\n".join(f"- {item}" for item in r.meta.limitations),
            references="\n".join(f"- <{url}>" for url in r.meta.references),
        )
        for r in rules
    )

    return (
        HEADER.format(
            family=family.value,
            heading=blurb.heading,
            summary=blurb.summary.format(count=len(rules)),
            scope=blurb.scope,
            index=index,
        )
        + body
    )


def pages() -> dict[Path, str]:
    return {
        DOCS / f"{family.value}.md": render(family, rules)
        for family, rules in documented_families().items()
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()

    rendered = pages()

    if args.check:
        stale = [
            path
            for path, text in rendered.items()
            if (path.read_text(encoding="utf-8") if path.exists() else "") != text
        ]
        # A page for a family that no longer has rules is as wrong as a stale
        # one, and deleting the last rule of a family is exactly when nobody
        # thinks to look in docs/.
        orphaned = sorted(p for p in DOCS.glob("*.md") if p not in rendered)
        for path in stale:
            print(
                f"RULE DOCS STALE: {path.relative_to(DOCS.parent.parent)} does not match "
                "the registry; run scripts/gen_rule_docs.py",
                file=sys.stderr,
            )
        for path in orphaned:
            print(
                f"RULE DOCS ORPHANED: {path.relative_to(DOCS.parent.parent)} documents a "
                "family with no rules",
                file=sys.stderr,
            )
        if stale or orphaned:
            return 1

        counted = ", ".join(f"{p.stem} {t.count('\n### ')}" for p, t in rendered.items())
        total = sum(text.count("\n### ") for text in rendered.values())
        print(f"rule docs current: {total} rules documented ({counted})")
        return 0

    DOCS.mkdir(parents=True, exist_ok=True)
    for path, text in rendered.items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(DOCS.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
